# Generated by Django 2.0.4 on 2018-06-25 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='data de partida')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('matricula', models.IntegerField(verbose_name='matrícula')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=200, verbose_name='destino')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='observação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='data da solicitação')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Funcionario')),
            ],
            options={
                'verbose_name_plural': 'solicitações',
                'verbose_name': 'solicitação',
                'ordering': ['solicitante__nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('combustivel', models.CharField(max_length=200, verbose_name='combustível')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('chassi', models.CharField(max_length=17, unique=True)),
                ('ano', models.IntegerField()),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'veículo',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Funcionario'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='solicitacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Solicitacao'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacao.Veiculo'),
        ),
    ]
